export { HashRouter as DynamicRouter } from "react-router-dom";
export {
    Culture,
    Dictionary,
    DateTime,
    Database,
    Dispatcher,
    Err,
    FieldType,
    ILocale,
    IQueryRequest,
    IDeleteResult,
    IQueryResult,
    IValidationError,
    IVocabs,
    Mime,
    Model,
    sanitizePhoneNumber,
    Schema,
    Translate,
    ValidationError,
} from "@vesta/core-es5";
